services:

  backend-livres:
    build: ./backend-livres
    container_name: backend_livres
    ports:
      - "8000:8000"

  backend-utilisateurs:
    build: ./backend-utilisateurs
    container_name: backend_utilisateurs
    ports:
      - "8001:8000"

  backend-emprunts:
    build: ./backend-emprunts
    container_name: backend_emprunts
    ports:
      - "8002:8000"